name: Daily Discord Message

on:
  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Discord servers
        run: |
          MESSAGE='{"content":"今日もない感じか"}'

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "$MESSAGE" \
          ${{ secrets.DISCORD_WEBHOOK }}

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "$MESSAGE" \
          ${{ secrets.DISCORD_WEBHOOK_2 }}

          curl -H "Content-Type: application/json" \
          -X POST \
          -d "$MESSAGE" \
          ${{ secrets.DISCORD_WEBHOOK_3 }}
